### ISSUE TITLE
getting error when testing with config file

### ISSUE THREAD

**Issue by andrewm659** [pryorda/vmware_exporter#122]
I have created the config.yml file from the example provided.  However I am getting this error.  

I am using CentOS 7 latest.

/opt/prometheus/vmware_exporter/vmware_exporter.py -c /opt/prometheus/vmware_exporter/config.yml
  File "/opt/prometheus/vmware_exporter/vmware_exporter.py", line 219
    return list(metrics.values())   # noqa: F705
SyntaxError: 'return' with argument inside generator

Here is the config.yml
```
default:
    vsphere_host: "esx"
    vsphere_user: "root"
    vsphere_password: "password"
    ignore_ssl: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True

esx:
    vsphere_host: 10.150.1.35
    vsphere_user: 'root'
    vsphere_password: 'password'
    ignore_ssl: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True

limited:
    vsphere_host: slowvc.example.com
    vsphere_user: 'administrator@vsphere.local'
    vsphere_password: 'password'
    ignore_ssl: True
    collect_only:
        vms: False
        vmguests: False
        datastores: True
        hosts: False
        snapshots: False

```
