### ISSUE TITLE
Question about scraping multiple vcenters

### ISSUE THREAD

**Issue by DirkFries** [pryorda/vmware_exporter#140]
I have seen on the projet page that it is possible to scrape mutiple vcenters.

So I set up my config.yml file likfe this:

```
default:
    vsphere_host: "vcenter"
    vsphere_user: ""
    vsphere_password: ""
    ignore_ssl: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: False

vcenter1:
    vsphere_host: "vcenter1"
    vsphere_user: ""
    vsphere_password: ""
    ignore_ssl: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: False

vcenter2:
    vsphere_host: "vcenter2"
    vsphere_user: ""
    vsphere_password: ""
    ignore_ssl: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: False

vcenterora:
    vsphere_host: "vcenterora"
    vsphere_user: ""
    vsphere_password: ""
    ignore_ssl: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: False
```

When I start vmware_expoerter I can see in the output that it only scrapes the "default" section. No matter if this section is the first one oder last one.

I am pretty sure I am just missing some little snipper, but I just can't find it.

**Comment by pryorda** [comment]
What are you setting your target to in the url?

**Comment by DirkFries** [comment]
Hi pryorda,

I'm not quite sure what you mean. What URL do you mean ? I the config file ?

**Comment by pryorda** [comment]
In the readme it describes how to switch sections and targets. Let me know if you still have trouble.

**Comment by safadig** [comment]
running the command
` vmware_exporter -c /etc/alertmanager/config.yml`
only goes through the Default

**Comment by solipsist01** [comment]
i found out you can have more vcenter hosts in the default configuration

```
default:
    vsphere_host: "vc1"
    vsphere_user: "yadda"
    vsphere_password: "yadda"
    vsphere_host: "vc2"
    vsphere_user: "yadda"
    vsphere_password: "yadda"
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True
```
