### ISSUE TITLE
Missing vmware_vm_disk_* metrics for some vms

### ISSUE THREAD

**Issue by jdelvecchio** [pryorda/vmware_exporter#170]
Hi,

I can't seem to have the following metrics in prometheus on all VMs :
- vmware_vm_disk_read_average
- vmware_vm_disk_write_average
- vmware_vm_disk_usage_average

In my environment, when I query another metric like vmware_vm_cpu_usage_average, you can see there is 2075 time series :
![image](https://user-images.githubusercontent.com/11552866/70517491-f32aac00-1b38-11ea-9126-b86a6adb5f75.png)

But with the metric vmware_vm_disk_read_average, only 45 time series :
![image](https://user-images.githubusercontent.com/11552866/70517465-ec9c3480-1b38-11ea-99a9-9f69aa82e77b.png)

Is this normal ? In what case vmware_exporter doesn't show the disk_read/write metrics on a vm ?

Thanks a lot.
Julien

**Comment by jdelvecchio** [comment]
Actually #116 talks about it, sorry just saw it.

**Comment by jdelvecchio** [comment]
Re-opening this I can't re-open issue 116

**Comment by jdelvecchio** [comment]
Re-opening this one since I can't re-open issue 116

**Comment by fernandogarciaferna** [comment]
I have the same issue with:
 
- vmware_vm_guest_disk_free
- vmware_vm_guest_disk_capacity

The exporter only reads 44 values, how can I change this setting?

Regards.
Fernando.

**Comment by jdelvecchio** [comment]
@fernandogarciaferna those metrics are only gathered if you have vmware tools on your VMs

**Comment by vterdunov** [comment]
All VMS have VMware Tools. But the `vmware_vm_guest_disk_free` `vmware_vm_guest_disk_capacity` are empty.
Exporter version: v0.11.1
vSphere version: 6.7U3

Any suggestions?

**Comment by hbermudez-stratio** [comment]
Hi:

I have the next scenario:

- vSphere 6.7
- vmware_exporter v0.16.1 (dockerhub image)
- Next config File:
```
default:
    vsphere_host: "xxx.xxxx.xxx"
    vsphere_user: "xxxxxx@xxxxxx.xxx"
    vsphere_password: "xxx"
    ignore_ssl: True
    specs_size: 50000
    fetch_custom_attributes: True
    fetch_tags: False
    fetch_alarms: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True
```

And I have missing metrics to, not only disk, `vmware_vm_boot_timestamp_seconds` too for example (the VM is UP). Here i can see the metric where vmware tools are in the VM but the exporter doesn't get all metric. Here an example:
```
vmware_vm_guest_tools_running_status{cluster_name="ClusterC",dc_name="Stratio.com",host_name="esx01c.int.stratio.com",tools_status="toolsOk",vm_name="AppsInt-private12"} 1.0
vmware_vm_power_state{cluster_name="ClusterC",dc_name="Stratio.com",host_name="esx01c.int.stratio.com",vm_name="AppsInt-private12"} 1.0
vmware_vm_num_cpu{cluster_name="ClusterC",dc_name="Stratio.com",host_name="esx01c.int.stratio.com",vm_name="AppsInt-private12"} 10.0
.
.
.
vmware_vm_net_droppedTx_summation{cluster_name="ClusterC",dc_name="Stratio.com",host_name="esx01c.int.stratio.com",vm_name="AppsInt-private12"} 0.0
```
But the metric `vmware_vm_boot_timestamp_seconds` isn't there. Any idea if this is a bug or a bad configuration?

Thanks.
