### ISSUE TITLE
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this

### ISSUE THREAD

**Issue by linhuisheng** [pryorda/vmware_exporter#213]
I use promethues cluster（two promethues） ,Two separately fetch data from vmware_exporter, 20 seconds apart, report this error, and then report all the way, can't do it any more. I  should 30s collect it

File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1071, in finish
"Request.finish called on a request after its connection was lost; "
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

my prometheus.yml:
global:
scrape_interval: 2m
evaluation_interval: 2m
scrape_timeout: 2m
external_labels:
dc: europe1

under the specific job: scrape_interval  should 30s,  how can I do?

**Comment by pryorda** [comment]
```
  - job_name: vmware_exporter
    relabel_configs:
...
    scrape_interval: 1m
    scrape_timeout: 1m
    static_configs:
    - targets:
      - blah
```
