### ISSUE TITLE
Getting metrics from more than one VCenter

### ISSUE THREAD

**Issue by bcochofel** [pryorda/vmware_exporter#23]
Hi,

I'm trying to configure the vmware_exporter to pull metrics from diferent vcenters, but I'm not getting the hang of the configuration on the prometheus server file. Is there any example for me to look?

Thanks,
Bruno

**Comment by akurach** [comment]
@bcochofel  in readme:

```
default:
    vsphere_host: "vcenter"
    vsphere_user: "user"
    vsphere_password: "password"
    ignore_ssl: False
    collect_only:
        vms: True
        datastores: True
        hosts: True

esx:
    vsphere_host: vc.example2.com
    vsphere_user: 'root'
    vsphere_password: 'password'
    ignore_ssl: True
    collect_only:
        vms: False
        datastores: False
        hosts: True

limited:
    vsphere_host: slowvc.example.com
    vsphere_user: 'administrator@vsphere.local'
    vsphere_password: 'password'
    ignore_ssl: True
    collect_only:
        vms: False
        datastores: True
        hosts: False
```

**Comment by akurach** [comment]
I use different exporters for each VC

prom file looks like 

```
- job_name: vmware_export
    metrics_path: /metrics
    static_configs:
    - targets:
      - sdc-vc01
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: exporter_ip:9272

  - job_name: vmware_export_cod
    metrics_path: /metrics
    static_configs:
    - targets:
      - kr01-vc01
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: exporter_ip:9273
```

If you configure 1 exporter for many VC, try to list them in 
```
static_configs:
    - targets:
```

**Comment by bcochofel** [comment]
Hi,

Thanks for the quick answer.

What I'm trying to configure is one job with several sections. I have one target running vmware_exporter with a config file to get metrics from 5 vcenters. 
On the server side we need to have several section params, right? This is my problem, I don't know how to do this the right way :-)

Thanks,
Bruno

**Comment by bcochofel** [comment]
Hi,

I have now something working, but it's not quite what I want.

prometheus.yml:
  - job_name: 'vmware_exporter'
    scrape_interval:     300s
    file_sd_configs:
    - files:
      - vmware.exporter.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: remotehost:9272

vmware.exporter.yml   
- targets: ['remotehost:9272']
  labels:
    vcenter: vcenter01
    __param_section: default

- targets: ['remotehost:9272']
  labels:
    vcenter: vcenter02
    __param_section: vcenter02

- targets: ['remotehost:9272']
  labels:
    vcenter: vcenter03
    __param_section: vcenter03

- targets: ['remotehost:9272']
  labels:
    vcenter: vcenter04
    __param_section: vcenter04

But checking the status for the targets I have target and instance equal in all endpoints, and section and vcenter correclty set.

What am I missing?

Thanks,
Bruno

**Comment by pryorda** [comment]
@bcochofel Is it calling the same vcenter for each configuration? If so what does the vmware_exporter configuration look like? I haven't tried this script with multiple vcenters but switching targets should work. Do you have logs by chancee?

**Comment by bcochofel** [comment]
Hi,

Yes, I have the remotehost running vmware_exporter and getting metrics from more than one vcenter.

Here's the config.yml file from vmware_exporter:

default:
    vsphere_host: vcenter01
    vsphere_user: user
    vsphere_password: pass
    ignore_ssl: True
    collect_only:
        vms: False
        datastores: True
        hosts: True

vcenter02:
    vsphere_host: vcenter02
    vsphere_user: user
    vsphere_password: pass
    ignore_ssl: True
    collect_only:
        vms: False
        datastores: True
        hosts: True

vcenter03:
    vsphere_host: vcenter03
    vsphere_user: user
    vsphere_password: pass
    ignore_ssl: True
    collect_only:
        vms: False
        datastores: True
        hosts: True

vcenter04:
    vsphere_host: vcenter04
    vsphere_user: user
    vsphere_password: pass
    ignore_ssl: True
    collect_only:
        vms: False
        datastores: True
        hosts: True

**Comment by pryorda** [comment]
Since you're running it via prometheus and using ?target= can you remove the VCENTER_HOST entry from the default section.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bcochofel** [comment]
Hi,

I can remoev that from default, but the issue stays the same. I have the instance name of the remotehost, not the vcenterN.

Bruno

**Comment by pryorda** [comment]
Can you do curl vmware_exporter:9292/metrics?target=vcenter02&section=vcenter02

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bcochofel** [comment]
Hi @pryorda ,

no I'm not able to curl that :-(

**Comment by bcochofel** [comment]
Hi,

Ok, I am able to get metrics from all vcenter using http://remotehost:9272/metrics?section=vcenterN

I just need to be able to configure on the prometheus server to get this.

**Comment by akurach** [comment]
@bcochofel try smth like this
```
- job_name: vmware_export
    metrics_path: /metrics
    static_configs:
    - targets:
      - vcenter01
      - vcenter02
      - vcenter03
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: exporter_ip:9272
```

**Comment by bcochofel** [comment]
Hi,

Super, it works.

thank you so much @pryorda 

Bruno

**Comment by pryorda** [comment]
Thank @akurach he helped more :). 

+1 @akurach Thanks for helping out.

**Comment by bcochofel** [comment]
Ok, I've found a little issue with this approach. I believe it's only using the default section on the config.yml file for the vmware_exporter.

If I change something like vms: True on a specific section it doesn't work, but if I change this on the default section it works, but changes the behavior for all sections.

Can we use, besides the target, the section also?

One more thing, is there a way to get IO Wait info for the ESXi hosts? :-)

Thanks,
Bruno

**Comment by pryorda** [comment]
Create a feature request for the io wait as that will be an additional metric. Typically the iowait in the vms is will tell you something. 

You should be able to pass param - section in the prometheus configuration. I use telegraf to query my exporter and it sets all my information. 

I dont have multiple vcenters so its a bit hard for me to diag.

**Comment by bcochofel** [comment]
Hi,

I'm gonna try and pass the param section on the prometheus configuration.

And yes, thank you both for helping out. :-)

**Comment by pryorda** [comment]
@bcochofel if that doesn't work, create a bug report for the section toggle and I'll update the code if it needs it.

**Comment by bcochofel** [comment]
Hi,

I think I need help for that :-)

I'm new to prometheus. How can I pass the section parameter on the config?

Thanks,
Bruno

**Comment by bcochofel** [comment]
Hi,

I've managed to configure prometheus to pass section on the url so now everything is working as expected.

Thank you all for the help.
Bruno

**Comment by CrashLaker** [comment]
Hi all.
although this is super helpful
```yaml
- job_name: vmware_export
    metrics_path: /metrics
    static_configs:
    - targets:
      - vcenter01
      - vcenter02
      - vcenter03
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: exporter_ip:9272
```

how would I do when I have different target_label IPs for each target?
i've created 1 container per esxi host exporter

**Comment by BHAARATH002** [comment]
Hi,
I'm trying to run the config and the service is up but when i tried to curl i get the following
curl http://localhost:9272/metrics
No vsphere_host or target defined!

```
default:
  vsphere_host: 'https://ussd-tst-vmvc01.illumina.com/sdk'
  vsphere_user: 'xxxxxx
  vsphere_password: 'xxxxxx'
  ignore_ssl: True
  collect_only:
      vms: False
      vmguests: False
      datastores: True
      hosts: True
      snapshots: False
```

Is it possible to use the url in vshpere_host variable?
If not how can I use the url?
