### ISSUE TITLE
Alarms no metrics created

### ISSUE THREAD

**Issue by davidjveer** [pryorda/vmware_exporter#230]
Hey there!  We've configured the exporter and have `fetch_alarms: True` set in our configuration but are not getting any metrics with Alarm data when we scrape our vCenters despite getting all of the other metrics we'd expect.  During this, we did have 3 alarms active (2 Critical, 1 Warning) that were unacknowledged so we would expect to have metric data returned for this.  Are we missing something? Thanks!

**Comment by davidjveer** [comment]
Our configuration looks like this:
```
default:
    vsphere_host: "vcenter.fqdn.com"
    vsphere_user: "user"
    vsphere_password: "password"
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: True
    collect_only:
        vms: False
        vmguests: False
        datastores: True
        hosts: True
        snapshots: True
```
