### ISSUE TITLE
Hosts list in data collection configuration

### ISSUE THREAD

**Issue by maxkushnir** [pryorda/vmware_exporter#257]
Is it possible to change the logic of work with the config file to use a list of hosts with the same parameters of collection instead of a separate config per host?

_Example:_
```
default:
    vsphere_host: ["vc.example1.com", "vc.example2.com", "vc.example3.com"]
    vsphere_user: "user"
    vsphere_password: "password"
    ignore_ssl: False
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: False
    fetch_alarms: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: False

```
Currently, this is not possible: `builtins.TypeError: expected string or bytes-like object`.
