### ISSUE TITLE
HELP: Just can't figure out the configuration files

### ISSUE THREAD

**Issue by TheGabeMan** [pryorda/vmware_exporter#259]
Trying to get prometheus and vmware_explorer running in docker. Both containers are up and running, can reach their webpages, but I can't get any host collections. Read a few posts and blogpost but I can't seem to understand the relation and keep getting "No vsphere_host or target defined" errors.

My vmware-exporter config.yaml:

```
kind: ConfigMap
metadata:
  labels:
    app: vmware-exporter
  name: vmware-exporter-config
apiVersion: v1
data:
  VSPHERE_USER: "root"
  VSPHERE_PASSWORD: "xxxxxx"
  VSPHERE_HOST: 192.168.0.5
  VSPHERE_IGNORE_SSL: "True"
  VSPHERE_COLLECT_HOSTS: "True"
  VSPHERE_COLLECT_DATASTORES: "True"
  VSPHERE_COLLECT_VMS: "True"
```

My prometheus.yml:

```
`# my global config
global:
  scrape_interval:     1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'vmware_vcenter'
      # metrics_path: '/metrics'
      # scrape_timeout: 15s
    static_configs:
      - targets: ['172.17.0.8:9272']
   `
```

Target 172.170.0.8 is the vmware_explorer container.

The prometheus website shows me the healthy Prometheus target and unhealthy vmware_vcenter (0/1 up) with an error: "server returned HTTP status 500 Internal Server Error". 

I have no clue how the config files should connect. Is the job_name used in prometheus also used in vmware_explorer?
