### ISSUE TITLE
Variable Section in prometheus config.

### ISSUE THREAD

**Issue by solipsist01** [pryorda/vmware_exporter#305]
Hello.

Does one need to configure a prometheus job per vcenter if you want to monitore more vcenters ?
Wouldn't it be possible to configure section, as a variable ? or rewrite that as the address variable ?
If i name the sections the same as my target for example, i would need only one config

```
  - job_name: exporter
    scrape_interval: 60s
    scrape_timeout: 50s
    metrics_path: /metrics
    params:
      section: ['vc01.domain.local']     <---- perhaps this could be the 'target' variable ? Section named after the target so it would find it.
    static_configs:
    - targets:
      - vc01.domain.local
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]      <------ perhaps we could do something here to not use the actual param variable, but target var?
      target_label: instance
    - target_label: __address__
      replacement: vmware-exporter:9272

```

vmware.yml

```

default:
  yadda yadda

vc01.domain.local:
    vsphere_host: "vc01.domain.local"
    vsphere_user: "monitor@vsphere.local"
    vsphere_password: "yadda"
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True
```

**Comment by Roemer** [comment]
I'm wondering the same. Did you find something already?

**Comment by Roemer** [comment]
I tried it with:
```
  - job_name: vmware_export
    scrape_interval: 120s
    metrics_path: /metrics
    static_configs:
      - targets:
        - srv1
        - srv3
        - srv4
        - srv6
        - srv7
        - srv8
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_section
    - source_labels: [__param_section]
      target_label: instance
    - target_label: __address__
      replacement: vmware-exporter:9272
```
and it seems to work great. I actually only replaced the `__params` part and renamed `target` to `section`.
