### ISSUE TITLE
cpu.usage.average questions

### ISSUE THREAD

**Issue by aarismendi** [pryorda/vmware_exporter#337]
Hi, when I use powercli to query for `cpu.usage.average` I get back a number 0-100 for each CPU instance and a total value for all CPUs having a null instance since the metric is a percent. https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.monitoring.doc/GUID-A6DA012E-D0CE-478B-9525-8B4703813542.html

```
$h | get-stat -Realtime -Stat cpu.usage.average -MaxSamples 1                                                                   

MetricId                Timestamp                          Value Unit     Instance
--------                ---------                          ----- ----     --------
cpu.usage.average       10/25/2022 12:49:20 PM             17.68 %        37
cpu.usage.average       10/25/2022 12:49:20 PM             38.56 %        1
cpu.usage.average       10/25/2022 12:49:20 PM              13.1 %        9
cpu.usage.average       10/25/2022 12:49:20 PM              15.2 %        29
```

When I tried vmware_exporter with the config below I get a single result per host instead of a result for each instance plus the overall result e.g. 

`vmware_host_cpu_usage_average{cluster_name="mycluster",dc_name="mydatacenter",host_name="myserver"} 3654.0`

So my questions are:

1. Why is the value returned by vmware_exporter not the same as that returned by powercli?
2. Is there a way to export a value for each instance? (e.g. each CPU core)

vmware_exporter config:

```
default:
    vsphere_host: "vc"
    vsphere_user: "myuser
    vsphere_password: "mypass"
    ignore_ssl: True
    specs_size: True
    fetch_custom_attributes: True
    fetch_tags: False
    fetch_alarms: False
    collect_only:
        vms: False
        vmguests: False
        datastores: True
        hosts: True
        snapshots: False
```
