### ISSUE TITLE
Logs error in defer.py

### ISSUE THREAD

**Issue by n1nj444** [pryorda/vmware_exporter#352]
Hi guys,

The exporter works well but I got a lot of errors : 

vmware_exporter: Unhandled error in Deferred:
vmware_exporter: Traceback (most recent call last):
vmware_exporter: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 62, in run
vmware_exporter: return f(*args, **kwargs)
vmware_exporter: File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1652, in _vmware_get_hosts
vmware_exporter: self.updateMetricsLabelNames(host_metrics, ['hosts'])
vmware_exporter: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1905, in unwindGenerator
vmware_exporter: return _cancellableInlineCallbacks(gen)
vmware_exporter: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1815, in _cancellableInlineCallbacks
vmware_exporter: _inlineCallbacks(None, gen, status)
vmware_exporter: --- <exception caught here> ---
vmware_exporter: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
vmware_exporter: result = current_context.run(gen.send, result)
vmware_exporter: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 62, in run
vmware_exporter: return f(*args, **kwargs)
vmware_exporter: File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1192, in updateMetricsLabelNames
vmware_exporter: metric._labelnames += customAttributesLabelNames
vmware_exporter: builtins.TypeError: can only concatenate tuple (not "list") to tuple

My config.yml : 

```
---
default:
    vsphere_user: ""
    vsphere_password: ""
    ignore_ssl: False
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: False
    fetch_alarms: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True

vcenterfr1:
    vsphere_host: "vcenter1"
    vsphere_user: ""
    vsphere_password: ""
    ignore_ssl: False
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: False
    fetch_alarms: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True

vcenternl1:
    vsphere_host: "vcenter2"
    vsphere_user: ""
    vsphere_password: ""
    ignore_ssl: False
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: False
    fetch_alarms: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True
```

Can you help me, please ?
