### ISSUE TITLE
Boot time metric doesn't show all running VMs 

### ISSUE THREAD

**Issue by gprakosa** [pryorda/vmware_exporter#355]
Hi, I have 73 VMs running but just 47 VM have boot time value. Anyone experience same issue? 

Both exporter & prometheus are on k8s 1.25.4 with Image Tag v0.18.4 with following configuration:
```
data:
  ...
  VSPHERE_IGNORE_SSL: "True"
  VSPHERE_COLLECT_HOSTS: "True"
  VSPHERE_COLLECT_DATASTORES: "False"
  VSPHERE_COLLECT_VMS: "True"
  VSPHERE_COLLECT_VMGUESTS: "False"
  VSPHERE_COLLECT_SNAPSHOTS: "False"
  VSPHERE_FETCH_ALARMS: "True"
```

![image](https://user-images.githubusercontent.com/6815935/211694475-6c3ad561-c305-4f52-b6bf-dac40b2ca266.png)
