### ISSUE TITLE
I have got a bug or i don't understood how it works

### ISSUE THREAD

**Issue by REDEMBER34** [pryorda/vmware_exporter#389]
HI,  i see metrics into two section. When go to the url http://localhost:9272/metrics?section=default and ?section=limited. I see all metrics, but when i will try adding path  in prometheus.yml i see only metrics in ?section=default and i don't see path with ?section=limited
JFYI i used systemd. And it my prometheus config 
```
- job_name: vm_exp
    metrics_path: /metrics
    static_configs:
    - targets:
      - 'limited'
      - 'default'
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9272
```
