### ISSUE TITLE
Failed, Please help

### ISSUE THREAD

**Issue by fhc5326** [pryorda/vmware_exporter#401]
[user@promeoppo ~]$ vmware_exporter -c config.yml 
2025-05-16 17:31:36,617 INFO:Starting web server on port :9272
2025-05-16 17:31:40,568 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/vmware_exporter-0.18.4-py3.9.egg/vmware_exporter/vmware_exporter.py", line 1937, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.9/site-packages/twisted-24.11.0-py3.9.egg/twisted/internet/defer.py", line 2017, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/local/lib/python3.9/site-packages/vmware_exporter-0.18.4-py3.9.egg/vmware_exporter/vmware_exporter.py", line 1973, in generate_latest_metrics
    self.config[section]['collect_only'],
KeyError: 'collect_only'

Please help.

**Comment by thuvh** [comment]
i think you should add 'collect_only' in the section as an example in README

```
limited:
    vsphere_host: slowvc.example.com
    vsphere_user: 'administrator@vsphere.local'
    vsphere_password: 'password'
    ignore_ssl: True
    specs_size: 5000
    fetch_custom_attributes: True
    fetch_tags: True
    fetch_alarms: False
    collect_only:
        vms: False
        vmguests: False
        datastores: True
        hosts: False
        snapshots: False
```
