### ISSUE TITLE
Issues passing config file using docker

### ISSUE THREAD

**Issue by callahan22** [pryorda/vmware_exporter#91]
Or I'm just not understanding it....

Running a docker install of Prometheus.
Relevant parts of my docker-compose file:
```
  prometheus:
    image: prom/prometheus:v2.6.1
    container_name: prometheus
#    deploy:
#      mode: replicated
#      replicas: 2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    ports:
     - "9090:9090"

  vmware-exporter:
    image: pryorda/vmware_exporter
    container_name: vmware-exporter
    restart: unless-stopped
    ports:
      - '9272:9272'
    volumes:
      - ./vmware-exporter/config.yml:/opt/vmware_exporter/config.yml
    command:
      - '-c /opt/vmware_exporter/config.yml'
```

nano ./vmware-exporter/config.yml
```
default:
    vsphere_host: '1.2.3.2'
    vsphere_user: 'root'
    vsphere_password: 'password'
    ignore_ssl: True

ESXi-1.2.3.3:
    vsphere_host: '1.2.3.3'
    vsphere_user: 'root'
    vsphere_password: 'password'
    ignore_ssl: True

ESXi-1.2.3.4:
    vsphere_host: '1.2.3.4'
    vsphere_user: 'root'
    vsphere_password: 'password'
    ignore_ssl: True
```

nano ./prometheus/prometheus.yml

```
# VSphere ESXi
  - job_name: 'ESXi'
    metrics_path: '/metrics'
    file_sd_configs:
      - files:
        - /etc/prometheus/esx.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9272
```

nano ./prometheus/esx.yml

```
- targets:
    - 1.2.3.3
  labels:
    name: 'ESXi-1.2.3.3'
    group: 'ESXi Servers'

- targets:
    - 1.2.3.4
  labels:
    name: 'ESXi-1.2.3.4'
    group: 'ESXi Servers'
```

When running docker-compose up -d, I get the following error.

`FileNotFoundError: [Errno 2] No such file or directory: ' /opt/vmware_exporter/config.yml'
`

So, I comment out:
```
    command:
      - '-c /opt/vmware_exporter/config.yml'
```
and add:

```
environment:
       - VSPHERE_USER=root
       - VSPHERE_HOST=1.2.3.2
       - VSPHERE_PASSWORD=password
       - VSPHERE_IGNORE_SSL=True
```

just to get things running.

So now, I can exec into the vmware-exporter container and run ls:

```
sudo docker exec -it vmware-exporter /bin/sh
/opt/vmware_exporter # ls
CHANGELOG.md            MANIFEST.in             config.yml              requirements-tests.txt  setup.py                vmware_exporter
Dockerfile              README.md               dashboards              requirements.txt        systemd
LICENSE                 alerts                  kubernetes              setup.cfg               tests
```
The config file is there. A cat of the config file confirms it's mapped properly from the bind mount.
So I'm now at a loss as to why it can't find it a start up when I define the complete path in the environment variable.

Everything essentially works. The only issue is that I can only pull stats from one host as defined in the environment variables. I assumed it would walk though all of the targets defined in esx.yml but it's not.
I also assumed that I should have used:

```
params:
      section: [esx]
```

in the prometheus.yml file but in doing that, I would only be able to point it at one host which defeats the object of being able to point it at a file using file_sd_configs. I also tried using the section parameter more than once but that failed. Also adding the hosts as an array in the [] failed.

I'm clearly missing something so if anyone would like to enlighten me, I'd appreciate it. :-)

**Comment by callahan22** [comment]
Issue solved. For those with the same setup/issues....

The issue was multiple points. The config file had a typo. I needed to define it as:
```
command:
      -c /opt/vmware_exporter/config.yml
```
I also needed to define 2 entries separately in my prometheus.yml file (I was expecting it to work the way Prometheus handles a single file with multiple targets). It now looks like the config shown below. The "params" is also required.

```
# ESXi-1-1.2.3.4
  - job_name: 'ESXi-1-1.2.3.4'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - '1.2.3.4'
    params:
      section: [ESXi-1-1.2.3.4]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: myserver.mycompany.com:9272

# ESXi-1-1.2.3.5
  - job_name: 'ESXi-1-1.2.3.5'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - '1.2.3.5'
    params:
      section: [ESXi-1-1.2.3.4]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: myserver.mycompany.com:9272
```
Restart your Prometheus container and you should now see 2 separate entries for your 2 or more ESXi servers.
